# Connects all Lotus daemons to each other. This is required for the nodes to be able to sync their state.
# It assumes the daemons and the bootstrap are up and running (but not necessarily the validators)

---
- name: Connect lotus daemons to each other
  hosts: all
  gather_facts: False
  become: False
  tasks:

    - name: Collect Lotus daemon addresses
      ansible.builtin.fetch:
        src: .lotus/lotus-addr
        dest: tmp-lotus-addrs


    - name: Combine Lotus daemon addresses into a single file
      run_once: True
      delegate_to: localhost
      shell: 'rm -f lotus-addrs && cat tmp-lotus-addrs/*/.lotus/lotus-addr >> lotus-addrs && rm -r tmp-lotus-addrs'


    - name: Copy Lotus daemon address file to all nodes
      ansible.builtin.copy:
        src: lotus-addrs
        dest: .lotus/


    - name: Connect all Lotus daemons to each other
      ansible.builtin.script:
        cmd: scripts/connect-daemon.sh
...
