# Runs the scripts/custom.sh script. This is meant as a convenience tool for executing ad-hoc scripts.
#
# Applies to all hosts by default, unless other nodes are specified using --extra-vars "nodes=..."

---
- name: Run custom script
  hosts: "{{nodes | default('all')}}"
  gather_facts: False
  become: False
  tasks:
    - name: "Run custom script"
      ansible.builtin.script:
        cmd: scripts/custom.sh
...