# Deploys the whole system from scratch.
# Performs a deep clean by running deep-clean.yaml
# (potentially producing and ignoring some errors, if nothing is running on the hosts - this is normal)
# and sets up a new Spacenet deployment.
#
# The nodes variable must not be set, as this playbook must distinguish between different kinds of nodes
# (such as bootstrap and validators).

---
- hosts: all
  gather_facts: False
  tasks:
    - name: Verify that nodes variable is not defined
      fail: msg="Variable nodes must not be defined (nodes set to '{{ nodes }}')"
      when: nodes is defined

- import_playbook: deep-clean.yaml
- import_playbook: setup.yaml
- import_playbook: deploy-current.yaml
...
