# Generates a new genesis block (at the bootstrap node) and copies it to all validators.
# Assumes the hosts to have already been set up (using setup.yaml).
#
# An alternative set of nodes to copy the genesis block to can be specified using --extra-vars "nodes=..."

---
- name: Generate new Lotus genesis block
  hosts: bootstrap[0]
  gather_facts: False
  become: False
  tasks:

    - name: Copy genesis template to the node
      ansible.builtin.copy:
        src: spacenet_template.json
        dest: lotus/spacenet_template.json

    - name: Run genesis generation script
      ansible.builtin.script:
        cmd: scripts/generate-genesis.sh spacenet-genesis.car spacenet_template.json

    - name: Fetch genesis file
      ansible.builtin.fetch:
        flat: True
        src: lotus/spacenet-genesis.car
        dest: spacenet-genesis.car


- name: Distribute genesis block to all Lotus nodes
  hosts: "{{nodes | default('all')}}"
  gather_facts: False
  become: False
  tasks:

    - name: Copy genesis file to all nodes
      ansible.builtin.copy:
        src: spacenet-genesis.car
        dest: lotus/spacenet-genesis.car
...
