# Restarts a given set of validators.
# For safety, does NOT default to restarting all validators
# and the set of hosts to restart must be explicitly given using --extra-vars "nodes=..."
#
# Note that this playbook always affects all hosts, regardless of the value of the nodes variable.
# This is due to the necessity of reconnecting all daemons to the restarted one.

---
- name: Make sure nodes are specified explicitly
  hosts: "{{ nodes }}"
  gather_facts: False
  tasks:


- import_playbook: kill.yaml
- import_playbook: start-daemons.yaml


- name: Start only the specified validators
  hosts: "{{ nodes }}"
  gather_facts: False
  tasks:
    - name: Start validators
      ansible.builtin.script:
        cmd: scripts/start-validator.sh '{{ log_file_lines }}' '{{ max_log_archive_size }}'
...