# Sets up the environment for running the Lotus daemon and validator.
# This includes installing the necessary packages, fetching the Lotus code, and compiling it.
# It does not start any nodes. See start-* and deploy-*.yaml for starting the nodes.
#
# Applies to all hosts by default, unless other nodes are specified using --extra-vars "nodes=..."

---
- name: Initialize Mir benchmark VM
  hosts: "{{nodes | default('all')}}"
  gather_facts: False
  become: False
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/go/bin"
  tasks:

    - name: "Run apt update"
      become: True
      ansible.builtin.apt:
        update_cache: True


    - name: "Install apt packages"
      become: True
      ansible.builtin.apt:
        name:
          - mesa-opencl-icd
          - ocl-icd-opencl-dev
          - gcc
          - git
          - bzr
          - jq
          - pkg-config
          - curl
          - clang
          - build-essential
          - hwloc
          - libhwloc-dev
          - wget
          - make
          - golang
          - tmux
        state: present


    - name: "Run apt upgrade"
      become: True
      ansible.builtin.apt:
        upgrade: yes


    - name: Clone Lotus repo from GitHub
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: ~/lotus


    - name: "Check out the selected code version: {{ git_version }}"
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: ~/lotus
        single_branch: True
        version: "{{ git_version }}"
        force: True


    - name: compile spacenet code
      make:
        chdir: ~/lotus
        target: spacenet


    - name: "Run setup script"
      ansible.builtin.script:
        cmd: scripts/setup.sh
...
